# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tomas/Desktop/OpenHMD_ALL/OpenHMD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tomas/Desktop/OpenHMD_ALL/OpenHMD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tomas/Desktop/OpenHMD_ALL/OpenHMD/CMakeFiles /home/tomas/Desktop/OpenHMD_ALL/OpenHMD/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tomas/Desktop/OpenHMD_ALL/OpenHMD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openhmd-static

# Build rule for target.
openhmd-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openhmd-static
.PHONY : openhmd-static

# fast build rule for target.
openhmd-static/fast:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/build
.PHONY : openhmd-static/fast

#=============================================================================
# Target rules for targets named openhmd-shared

# Build rule for target.
openhmd-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openhmd-shared
.PHONY : openhmd-shared

# fast build rule for target.
openhmd-shared/fast:
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/build
.PHONY : openhmd-shared/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) -f examples/simple/CMakeFiles/simple.dir/build.make examples/simple/CMakeFiles/simple.dir/build
.PHONY : simple/fast

src/drv_3glasses/packet.o: src/drv_3glasses/packet.c.o

.PHONY : src/drv_3glasses/packet.o

# target to build an object file
src/drv_3glasses/packet.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_3glasses/packet.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_3glasses/packet.c.o
.PHONY : src/drv_3glasses/packet.c.o

src/drv_3glasses/packet.i: src/drv_3glasses/packet.c.i

.PHONY : src/drv_3glasses/packet.i

# target to preprocess a source file
src/drv_3glasses/packet.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_3glasses/packet.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_3glasses/packet.c.i
.PHONY : src/drv_3glasses/packet.c.i

src/drv_3glasses/packet.s: src/drv_3glasses/packet.c.s

.PHONY : src/drv_3glasses/packet.s

# target to generate assembly for a file
src/drv_3glasses/packet.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_3glasses/packet.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_3glasses/packet.c.s
.PHONY : src/drv_3glasses/packet.c.s

src/drv_3glasses/xgvr.o: src/drv_3glasses/xgvr.c.o

.PHONY : src/drv_3glasses/xgvr.o

# target to build an object file
src/drv_3glasses/xgvr.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_3glasses/xgvr.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_3glasses/xgvr.c.o
.PHONY : src/drv_3glasses/xgvr.c.o

src/drv_3glasses/xgvr.i: src/drv_3glasses/xgvr.c.i

.PHONY : src/drv_3glasses/xgvr.i

# target to preprocess a source file
src/drv_3glasses/xgvr.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_3glasses/xgvr.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_3glasses/xgvr.c.i
.PHONY : src/drv_3glasses/xgvr.c.i

src/drv_3glasses/xgvr.s: src/drv_3glasses/xgvr.c.s

.PHONY : src/drv_3glasses/xgvr.s

# target to generate assembly for a file
src/drv_3glasses/xgvr.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_3glasses/xgvr.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_3glasses/xgvr.c.s
.PHONY : src/drv_3glasses/xgvr.c.s

src/drv_deepoon/deepoon.o: src/drv_deepoon/deepoon.c.o

.PHONY : src/drv_deepoon/deepoon.o

# target to build an object file
src/drv_deepoon/deepoon.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_deepoon/deepoon.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_deepoon/deepoon.c.o
.PHONY : src/drv_deepoon/deepoon.c.o

src/drv_deepoon/deepoon.i: src/drv_deepoon/deepoon.c.i

.PHONY : src/drv_deepoon/deepoon.i

# target to preprocess a source file
src/drv_deepoon/deepoon.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_deepoon/deepoon.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_deepoon/deepoon.c.i
.PHONY : src/drv_deepoon/deepoon.c.i

src/drv_deepoon/deepoon.s: src/drv_deepoon/deepoon.c.s

.PHONY : src/drv_deepoon/deepoon.s

# target to generate assembly for a file
src/drv_deepoon/deepoon.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_deepoon/deepoon.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_deepoon/deepoon.c.s
.PHONY : src/drv_deepoon/deepoon.c.s

src/drv_deepoon/packet.o: src/drv_deepoon/packet.c.o

.PHONY : src/drv_deepoon/packet.o

# target to build an object file
src/drv_deepoon/packet.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_deepoon/packet.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_deepoon/packet.c.o
.PHONY : src/drv_deepoon/packet.c.o

src/drv_deepoon/packet.i: src/drv_deepoon/packet.c.i

.PHONY : src/drv_deepoon/packet.i

# target to preprocess a source file
src/drv_deepoon/packet.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_deepoon/packet.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_deepoon/packet.c.i
.PHONY : src/drv_deepoon/packet.c.i

src/drv_deepoon/packet.s: src/drv_deepoon/packet.c.s

.PHONY : src/drv_deepoon/packet.s

# target to generate assembly for a file
src/drv_deepoon/packet.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_deepoon/packet.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_deepoon/packet.c.s
.PHONY : src/drv_deepoon/packet.c.s

src/drv_dummy/dummy.o: src/drv_dummy/dummy.c.o

.PHONY : src/drv_dummy/dummy.o

# target to build an object file
src/drv_dummy/dummy.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_dummy/dummy.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_dummy/dummy.c.o
.PHONY : src/drv_dummy/dummy.c.o

src/drv_dummy/dummy.i: src/drv_dummy/dummy.c.i

.PHONY : src/drv_dummy/dummy.i

# target to preprocess a source file
src/drv_dummy/dummy.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_dummy/dummy.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_dummy/dummy.c.i
.PHONY : src/drv_dummy/dummy.c.i

src/drv_dummy/dummy.s: src/drv_dummy/dummy.c.s

.PHONY : src/drv_dummy/dummy.s

# target to generate assembly for a file
src/drv_dummy/dummy.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_dummy/dummy.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_dummy/dummy.c.s
.PHONY : src/drv_dummy/dummy.c.s

src/drv_external/external.o: src/drv_external/external.c.o

.PHONY : src/drv_external/external.o

# target to build an object file
src/drv_external/external.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_external/external.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_external/external.c.o
.PHONY : src/drv_external/external.c.o

src/drv_external/external.i: src/drv_external/external.c.i

.PHONY : src/drv_external/external.i

# target to preprocess a source file
src/drv_external/external.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_external/external.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_external/external.c.i
.PHONY : src/drv_external/external.c.i

src/drv_external/external.s: src/drv_external/external.c.s

.PHONY : src/drv_external/external.s

# target to generate assembly for a file
src/drv_external/external.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_external/external.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_external/external.c.s
.PHONY : src/drv_external/external.c.s

src/drv_htc_vive/packet.o: src/drv_htc_vive/packet.c.o

.PHONY : src/drv_htc_vive/packet.o

# target to build an object file
src/drv_htc_vive/packet.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_htc_vive/packet.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_htc_vive/packet.c.o
.PHONY : src/drv_htc_vive/packet.c.o

src/drv_htc_vive/packet.i: src/drv_htc_vive/packet.c.i

.PHONY : src/drv_htc_vive/packet.i

# target to preprocess a source file
src/drv_htc_vive/packet.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_htc_vive/packet.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_htc_vive/packet.c.i
.PHONY : src/drv_htc_vive/packet.c.i

src/drv_htc_vive/packet.s: src/drv_htc_vive/packet.c.s

.PHONY : src/drv_htc_vive/packet.s

# target to generate assembly for a file
src/drv_htc_vive/packet.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_htc_vive/packet.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_htc_vive/packet.c.s
.PHONY : src/drv_htc_vive/packet.c.s

src/drv_htc_vive/vive.o: src/drv_htc_vive/vive.c.o

.PHONY : src/drv_htc_vive/vive.o

# target to build an object file
src/drv_htc_vive/vive.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_htc_vive/vive.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_htc_vive/vive.c.o
.PHONY : src/drv_htc_vive/vive.c.o

src/drv_htc_vive/vive.i: src/drv_htc_vive/vive.c.i

.PHONY : src/drv_htc_vive/vive.i

# target to preprocess a source file
src/drv_htc_vive/vive.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_htc_vive/vive.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_htc_vive/vive.c.i
.PHONY : src/drv_htc_vive/vive.c.i

src/drv_htc_vive/vive.s: src/drv_htc_vive/vive.c.s

.PHONY : src/drv_htc_vive/vive.s

# target to generate assembly for a file
src/drv_htc_vive/vive.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_htc_vive/vive.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_htc_vive/vive.c.s
.PHONY : src/drv_htc_vive/vive.c.s

src/drv_nolo/nolo.o: src/drv_nolo/nolo.c.o

.PHONY : src/drv_nolo/nolo.o

# target to build an object file
src/drv_nolo/nolo.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nolo/nolo.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nolo/nolo.c.o
.PHONY : src/drv_nolo/nolo.c.o

src/drv_nolo/nolo.i: src/drv_nolo/nolo.c.i

.PHONY : src/drv_nolo/nolo.i

# target to preprocess a source file
src/drv_nolo/nolo.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nolo/nolo.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nolo/nolo.c.i
.PHONY : src/drv_nolo/nolo.c.i

src/drv_nolo/nolo.s: src/drv_nolo/nolo.c.s

.PHONY : src/drv_nolo/nolo.s

# target to generate assembly for a file
src/drv_nolo/nolo.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nolo/nolo.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nolo/nolo.c.s
.PHONY : src/drv_nolo/nolo.c.s

src/drv_nolo/packet.o: src/drv_nolo/packet.c.o

.PHONY : src/drv_nolo/packet.o

# target to build an object file
src/drv_nolo/packet.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nolo/packet.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nolo/packet.c.o
.PHONY : src/drv_nolo/packet.c.o

src/drv_nolo/packet.i: src/drv_nolo/packet.c.i

.PHONY : src/drv_nolo/packet.i

# target to preprocess a source file
src/drv_nolo/packet.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nolo/packet.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nolo/packet.c.i
.PHONY : src/drv_nolo/packet.c.i

src/drv_nolo/packet.s: src/drv_nolo/packet.c.s

.PHONY : src/drv_nolo/packet.s

# target to generate assembly for a file
src/drv_nolo/packet.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nolo/packet.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nolo/packet.c.s
.PHONY : src/drv_nolo/packet.c.s

src/drv_nxtvr/nxtvr.o: src/drv_nxtvr/nxtvr.c.o

.PHONY : src/drv_nxtvr/nxtvr.o

# target to build an object file
src/drv_nxtvr/nxtvr.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nxtvr/nxtvr.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nxtvr/nxtvr.c.o
.PHONY : src/drv_nxtvr/nxtvr.c.o

src/drv_nxtvr/nxtvr.i: src/drv_nxtvr/nxtvr.c.i

.PHONY : src/drv_nxtvr/nxtvr.i

# target to preprocess a source file
src/drv_nxtvr/nxtvr.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nxtvr/nxtvr.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nxtvr/nxtvr.c.i
.PHONY : src/drv_nxtvr/nxtvr.c.i

src/drv_nxtvr/nxtvr.s: src/drv_nxtvr/nxtvr.c.s

.PHONY : src/drv_nxtvr/nxtvr.s

# target to generate assembly for a file
src/drv_nxtvr/nxtvr.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nxtvr/nxtvr.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nxtvr/nxtvr.c.s
.PHONY : src/drv_nxtvr/nxtvr.c.s

src/drv_nxtvr/packet.o: src/drv_nxtvr/packet.c.o

.PHONY : src/drv_nxtvr/packet.o

# target to build an object file
src/drv_nxtvr/packet.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nxtvr/packet.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nxtvr/packet.c.o
.PHONY : src/drv_nxtvr/packet.c.o

src/drv_nxtvr/packet.i: src/drv_nxtvr/packet.c.i

.PHONY : src/drv_nxtvr/packet.i

# target to preprocess a source file
src/drv_nxtvr/packet.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nxtvr/packet.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nxtvr/packet.c.i
.PHONY : src/drv_nxtvr/packet.c.i

src/drv_nxtvr/packet.s: src/drv_nxtvr/packet.c.s

.PHONY : src/drv_nxtvr/packet.s

# target to generate assembly for a file
src/drv_nxtvr/packet.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_nxtvr/packet.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_nxtvr/packet.c.s
.PHONY : src/drv_nxtvr/packet.c.s

src/drv_oculus_rift/packet.o: src/drv_oculus_rift/packet.c.o

.PHONY : src/drv_oculus_rift/packet.o

# target to build an object file
src/drv_oculus_rift/packet.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_oculus_rift/packet.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_oculus_rift/packet.c.o
.PHONY : src/drv_oculus_rift/packet.c.o

src/drv_oculus_rift/packet.i: src/drv_oculus_rift/packet.c.i

.PHONY : src/drv_oculus_rift/packet.i

# target to preprocess a source file
src/drv_oculus_rift/packet.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_oculus_rift/packet.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_oculus_rift/packet.c.i
.PHONY : src/drv_oculus_rift/packet.c.i

src/drv_oculus_rift/packet.s: src/drv_oculus_rift/packet.c.s

.PHONY : src/drv_oculus_rift/packet.s

# target to generate assembly for a file
src/drv_oculus_rift/packet.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_oculus_rift/packet.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_oculus_rift/packet.c.s
.PHONY : src/drv_oculus_rift/packet.c.s

src/drv_oculus_rift/rift.o: src/drv_oculus_rift/rift.c.o

.PHONY : src/drv_oculus_rift/rift.o

# target to build an object file
src/drv_oculus_rift/rift.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_oculus_rift/rift.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_oculus_rift/rift.c.o
.PHONY : src/drv_oculus_rift/rift.c.o

src/drv_oculus_rift/rift.i: src/drv_oculus_rift/rift.c.i

.PHONY : src/drv_oculus_rift/rift.i

# target to preprocess a source file
src/drv_oculus_rift/rift.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_oculus_rift/rift.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_oculus_rift/rift.c.i
.PHONY : src/drv_oculus_rift/rift.c.i

src/drv_oculus_rift/rift.s: src/drv_oculus_rift/rift.c.s

.PHONY : src/drv_oculus_rift/rift.s

# target to generate assembly for a file
src/drv_oculus_rift/rift.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_oculus_rift/rift.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_oculus_rift/rift.c.s
.PHONY : src/drv_oculus_rift/rift.c.s

src/drv_psvr/packet.o: src/drv_psvr/packet.c.o

.PHONY : src/drv_psvr/packet.o

# target to build an object file
src/drv_psvr/packet.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_psvr/packet.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_psvr/packet.c.o
.PHONY : src/drv_psvr/packet.c.o

src/drv_psvr/packet.i: src/drv_psvr/packet.c.i

.PHONY : src/drv_psvr/packet.i

# target to preprocess a source file
src/drv_psvr/packet.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_psvr/packet.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_psvr/packet.c.i
.PHONY : src/drv_psvr/packet.c.i

src/drv_psvr/packet.s: src/drv_psvr/packet.c.s

.PHONY : src/drv_psvr/packet.s

# target to generate assembly for a file
src/drv_psvr/packet.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_psvr/packet.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_psvr/packet.c.s
.PHONY : src/drv_psvr/packet.c.s

src/drv_psvr/psvr.o: src/drv_psvr/psvr.c.o

.PHONY : src/drv_psvr/psvr.o

# target to build an object file
src/drv_psvr/psvr.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_psvr/psvr.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_psvr/psvr.c.o
.PHONY : src/drv_psvr/psvr.c.o

src/drv_psvr/psvr.i: src/drv_psvr/psvr.c.i

.PHONY : src/drv_psvr/psvr.i

# target to preprocess a source file
src/drv_psvr/psvr.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_psvr/psvr.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_psvr/psvr.c.i
.PHONY : src/drv_psvr/psvr.c.i

src/drv_psvr/psvr.s: src/drv_psvr/psvr.c.s

.PHONY : src/drv_psvr/psvr.s

# target to generate assembly for a file
src/drv_psvr/psvr.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_psvr/psvr.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_psvr/psvr.c.s
.PHONY : src/drv_psvr/psvr.c.s

src/drv_wmr/packet.o: src/drv_wmr/packet.c.o

.PHONY : src/drv_wmr/packet.o

# target to build an object file
src/drv_wmr/packet.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_wmr/packet.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_wmr/packet.c.o
.PHONY : src/drv_wmr/packet.c.o

src/drv_wmr/packet.i: src/drv_wmr/packet.c.i

.PHONY : src/drv_wmr/packet.i

# target to preprocess a source file
src/drv_wmr/packet.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_wmr/packet.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_wmr/packet.c.i
.PHONY : src/drv_wmr/packet.c.i

src/drv_wmr/packet.s: src/drv_wmr/packet.c.s

.PHONY : src/drv_wmr/packet.s

# target to generate assembly for a file
src/drv_wmr/packet.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_wmr/packet.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_wmr/packet.c.s
.PHONY : src/drv_wmr/packet.c.s

src/drv_wmr/wmr.o: src/drv_wmr/wmr.c.o

.PHONY : src/drv_wmr/wmr.o

# target to build an object file
src/drv_wmr/wmr.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_wmr/wmr.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_wmr/wmr.c.o
.PHONY : src/drv_wmr/wmr.c.o

src/drv_wmr/wmr.i: src/drv_wmr/wmr.c.i

.PHONY : src/drv_wmr/wmr.i

# target to preprocess a source file
src/drv_wmr/wmr.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_wmr/wmr.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_wmr/wmr.c.i
.PHONY : src/drv_wmr/wmr.c.i

src/drv_wmr/wmr.s: src/drv_wmr/wmr.c.s

.PHONY : src/drv_wmr/wmr.s

# target to generate assembly for a file
src/drv_wmr/wmr.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/drv_wmr/wmr.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/drv_wmr/wmr.c.s
.PHONY : src/drv_wmr/wmr.c.s

src/ext_deps/nxjson.o: src/ext_deps/nxjson.c.o

.PHONY : src/ext_deps/nxjson.o

# target to build an object file
src/ext_deps/nxjson.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/ext_deps/nxjson.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/ext_deps/nxjson.c.o
.PHONY : src/ext_deps/nxjson.c.o

src/ext_deps/nxjson.i: src/ext_deps/nxjson.c.i

.PHONY : src/ext_deps/nxjson.i

# target to preprocess a source file
src/ext_deps/nxjson.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/ext_deps/nxjson.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/ext_deps/nxjson.c.i
.PHONY : src/ext_deps/nxjson.c.i

src/ext_deps/nxjson.s: src/ext_deps/nxjson.c.s

.PHONY : src/ext_deps/nxjson.s

# target to generate assembly for a file
src/ext_deps/nxjson.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/ext_deps/nxjson.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/ext_deps/nxjson.c.s
.PHONY : src/ext_deps/nxjson.c.s

src/fusion.o: src/fusion.c.o

.PHONY : src/fusion.o

# target to build an object file
src/fusion.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/fusion.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/fusion.c.o
.PHONY : src/fusion.c.o

src/fusion.i: src/fusion.c.i

.PHONY : src/fusion.i

# target to preprocess a source file
src/fusion.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/fusion.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/fusion.c.i
.PHONY : src/fusion.c.i

src/fusion.s: src/fusion.c.s

.PHONY : src/fusion.s

# target to generate assembly for a file
src/fusion.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/fusion.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/fusion.c.s
.PHONY : src/fusion.c.s

src/omath.o: src/omath.c.o

.PHONY : src/omath.o

# target to build an object file
src/omath.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/omath.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/omath.c.o
.PHONY : src/omath.c.o

src/omath.i: src/omath.c.i

.PHONY : src/omath.i

# target to preprocess a source file
src/omath.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/omath.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/omath.c.i
.PHONY : src/omath.c.i

src/omath.s: src/omath.c.s

.PHONY : src/omath.s

# target to generate assembly for a file
src/omath.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/omath.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/omath.c.s
.PHONY : src/omath.c.s

src/openhmd.o: src/openhmd.c.o

.PHONY : src/openhmd.o

# target to build an object file
src/openhmd.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/openhmd.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/openhmd.c.o
.PHONY : src/openhmd.c.o

src/openhmd.i: src/openhmd.c.i

.PHONY : src/openhmd.i

# target to preprocess a source file
src/openhmd.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/openhmd.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/openhmd.c.i
.PHONY : src/openhmd.c.i

src/openhmd.s: src/openhmd.c.s

.PHONY : src/openhmd.s

# target to generate assembly for a file
src/openhmd.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/openhmd.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/openhmd.c.s
.PHONY : src/openhmd.c.s

src/platform-posix.o: src/platform-posix.c.o

.PHONY : src/platform-posix.o

# target to build an object file
src/platform-posix.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/platform-posix.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/platform-posix.c.o
.PHONY : src/platform-posix.c.o

src/platform-posix.i: src/platform-posix.c.i

.PHONY : src/platform-posix.i

# target to preprocess a source file
src/platform-posix.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/platform-posix.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/platform-posix.c.i
.PHONY : src/platform-posix.c.i

src/platform-posix.s: src/platform-posix.c.s

.PHONY : src/platform-posix.s

# target to generate assembly for a file
src/platform-posix.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/platform-posix.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/platform-posix.c.s
.PHONY : src/platform-posix.c.s

src/platform-win32.o: src/platform-win32.c.o

.PHONY : src/platform-win32.o

# target to build an object file
src/platform-win32.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/platform-win32.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/platform-win32.c.o
.PHONY : src/platform-win32.c.o

src/platform-win32.i: src/platform-win32.c.i

.PHONY : src/platform-win32.i

# target to preprocess a source file
src/platform-win32.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/platform-win32.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/platform-win32.c.i
.PHONY : src/platform-win32.c.i

src/platform-win32.s: src/platform-win32.c.s

.PHONY : src/platform-win32.s

# target to generate assembly for a file
src/platform-win32.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/platform-win32.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/platform-win32.c.s
.PHONY : src/platform-win32.c.s

src/shaders.o: src/shaders.c.o

.PHONY : src/shaders.o

# target to build an object file
src/shaders.c.o:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/shaders.c.o
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/shaders.c.o
.PHONY : src/shaders.c.o

src/shaders.i: src/shaders.c.i

.PHONY : src/shaders.i

# target to preprocess a source file
src/shaders.c.i:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/shaders.c.i
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/shaders.c.i
.PHONY : src/shaders.c.i

src/shaders.s: src/shaders.c.s

.PHONY : src/shaders.s

# target to generate assembly for a file
src/shaders.c.s:
	$(MAKE) -f CMakeFiles/openhmd-static.dir/build.make CMakeFiles/openhmd-static.dir/src/shaders.c.s
	$(MAKE) -f CMakeFiles/openhmd-shared.dir/build.make CMakeFiles/openhmd-shared.dir/src/shaders.c.s
.PHONY : src/shaders.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... openhmd-static"
	@echo "... edit_cache"
	@echo "... openhmd-shared"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... simple"
	@echo "... src/drv_3glasses/packet.o"
	@echo "... src/drv_3glasses/packet.i"
	@echo "... src/drv_3glasses/packet.s"
	@echo "... src/drv_3glasses/xgvr.o"
	@echo "... src/drv_3glasses/xgvr.i"
	@echo "... src/drv_3glasses/xgvr.s"
	@echo "... src/drv_deepoon/deepoon.o"
	@echo "... src/drv_deepoon/deepoon.i"
	@echo "... src/drv_deepoon/deepoon.s"
	@echo "... src/drv_deepoon/packet.o"
	@echo "... src/drv_deepoon/packet.i"
	@echo "... src/drv_deepoon/packet.s"
	@echo "... src/drv_dummy/dummy.o"
	@echo "... src/drv_dummy/dummy.i"
	@echo "... src/drv_dummy/dummy.s"
	@echo "... src/drv_external/external.o"
	@echo "... src/drv_external/external.i"
	@echo "... src/drv_external/external.s"
	@echo "... src/drv_htc_vive/packet.o"
	@echo "... src/drv_htc_vive/packet.i"
	@echo "... src/drv_htc_vive/packet.s"
	@echo "... src/drv_htc_vive/vive.o"
	@echo "... src/drv_htc_vive/vive.i"
	@echo "... src/drv_htc_vive/vive.s"
	@echo "... src/drv_nolo/nolo.o"
	@echo "... src/drv_nolo/nolo.i"
	@echo "... src/drv_nolo/nolo.s"
	@echo "... src/drv_nolo/packet.o"
	@echo "... src/drv_nolo/packet.i"
	@echo "... src/drv_nolo/packet.s"
	@echo "... src/drv_nxtvr/nxtvr.o"
	@echo "... src/drv_nxtvr/nxtvr.i"
	@echo "... src/drv_nxtvr/nxtvr.s"
	@echo "... src/drv_nxtvr/packet.o"
	@echo "... src/drv_nxtvr/packet.i"
	@echo "... src/drv_nxtvr/packet.s"
	@echo "... src/drv_oculus_rift/packet.o"
	@echo "... src/drv_oculus_rift/packet.i"
	@echo "... src/drv_oculus_rift/packet.s"
	@echo "... src/drv_oculus_rift/rift.o"
	@echo "... src/drv_oculus_rift/rift.i"
	@echo "... src/drv_oculus_rift/rift.s"
	@echo "... src/drv_psvr/packet.o"
	@echo "... src/drv_psvr/packet.i"
	@echo "... src/drv_psvr/packet.s"
	@echo "... src/drv_psvr/psvr.o"
	@echo "... src/drv_psvr/psvr.i"
	@echo "... src/drv_psvr/psvr.s"
	@echo "... src/drv_wmr/packet.o"
	@echo "... src/drv_wmr/packet.i"
	@echo "... src/drv_wmr/packet.s"
	@echo "... src/drv_wmr/wmr.o"
	@echo "... src/drv_wmr/wmr.i"
	@echo "... src/drv_wmr/wmr.s"
	@echo "... src/ext_deps/nxjson.o"
	@echo "... src/ext_deps/nxjson.i"
	@echo "... src/ext_deps/nxjson.s"
	@echo "... src/fusion.o"
	@echo "... src/fusion.i"
	@echo "... src/fusion.s"
	@echo "... src/omath.o"
	@echo "... src/omath.i"
	@echo "... src/omath.s"
	@echo "... src/openhmd.o"
	@echo "... src/openhmd.i"
	@echo "... src/openhmd.s"
	@echo "... src/platform-posix.o"
	@echo "... src/platform-posix.i"
	@echo "... src/platform-posix.s"
	@echo "... src/platform-win32.o"
	@echo "... src/platform-win32.i"
	@echo "... src/platform-win32.s"
	@echo "... src/shaders.o"
	@echo "... src/shaders.i"
	@echo "... src/shaders.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

